title: Demo Portfolio
email: your-email@example.com
description: Write an awesome description for your site. Edit this in _config.yml.
baseurl: "/DemoPortfolio"
url: "https://customcraft-software-llc.github.io"
github_username: jekyll
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/styles
  style: compressed
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - vendor
